Feature/be 06 manage bookmark
ChaRum-Capstone-Project-Batch-3/Backend pull request #13
Opened 2022-11-29 15:16 UTC by razanfawwaz

2022-11-29 16:54 UTC, timmtimm requested changes
mangat

2022-11-29 16:54 UTC, timmtimm commented on app/route/route.go
> +	user.POST("/bookmark/:thread_id", cl.BookmarkController.AddBookmark, authMiddleware.Check)
harusnya post si, btw alurnya yang kupikir pas di awal register langsung dibuatin bookmark aja, jadi bookmark user itu pasti ada

2022-11-29 16:54 UTC, timmtimm commented on business/bookmarks/domain.go
> +	Threads   []Thread
ini harusnya tipe data array primitive objectID, soalnya isi arraynya cuma id threadnya

2022-11-29 16:54 UTC, timmtimm commented on business/bookmarks/usecase.go
> +	if err != nil {
ini harusnya datanya memang gak ada/ketemu, kayanya coba dipastiin aja deh kalo user register itu ada dokumen bookmarknya

2022-11-29 17:01 UTC, razanfawwaz commented on business/bookmarks/domain.go
> +	Threads   []Thread
berarti gausah ngestore thread title ya?

2022-11-29 17:47 UTC, timmtimm commented on business/bookmarks/domain.go
> +	Threads   []Thread
gausah nanti kalo di get bookmarknya, nanti diganti responsenya, jadi dari id diganti ke thread gitu

2022-11-30 10:21 UTC, razanfawwaz commented on app/route/route.go
> +	user.POST("/bookmark/:thread_id", cl.BookmarkController.AddBookmark, authMiddleware.Check)
oke aku cobaa dulu

2022-12-08 16:16 UTC, closed without merging